@baseUrl = http://localhost:3000/api
@resourceName = products

# POST

# @name getAll
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=10
Content-Type: application/json

###

# @name filter
GET {{baseUrl}}/{{resourceName}}?color=cyan&color=magenta

###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
  "title": "This is Demo Add Post",
  "author": "Binh Tran"
}

###

# @name update
PATCH {{baseUrl}}/{{resourceName}}/1
Content-Type: application/json

{
  "title": "This is Demo Add Post New"
}

###
# @name delete
DELETE {{baseUrl}}/{{resourceName}}/2